//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaWebCambios.ServiceReferenceCambios {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCambios.WebServiceCambiosSoap")]
    public interface WebServiceCambiosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DolarToSoles", ReplyAction="*")]
        double DolarToSoles(double dolar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DolarToSoles", ReplyAction="*")]
        System.Threading.Tasks.Task<double> DolarToSolesAsync(double dolar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SolesToDolar", ReplyAction="*")]
        double SolesToDolar(double soles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SolesToDolar", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SolesToDolarAsync(double soles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setDtoS", ReplyAction="*")]
        void setDtoS(double mon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setDtoS", ReplyAction="*")]
        System.Threading.Tasks.Task setDtoSAsync(double mon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setStoD", ReplyAction="*")]
        void setStoD(double mon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setStoD", ReplyAction="*")]
        System.Threading.Tasks.Task setStoDAsync(double mon);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceCambiosSoapChannel : PaginaWebCambios.ServiceReferenceCambios.WebServiceCambiosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceCambiosSoapClient : System.ServiceModel.ClientBase<PaginaWebCambios.ServiceReferenceCambios.WebServiceCambiosSoap>, PaginaWebCambios.ServiceReferenceCambios.WebServiceCambiosSoap {
        
        public WebServiceCambiosSoapClient() {
        }
        
        public WebServiceCambiosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceCambiosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCambiosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCambiosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double DolarToSoles(double dolar) {
            return base.Channel.DolarToSoles(dolar);
        }
        
        public System.Threading.Tasks.Task<double> DolarToSolesAsync(double dolar) {
            return base.Channel.DolarToSolesAsync(dolar);
        }
        
        public double SolesToDolar(double soles) {
            return base.Channel.SolesToDolar(soles);
        }
        
        public System.Threading.Tasks.Task<double> SolesToDolarAsync(double soles) {
            return base.Channel.SolesToDolarAsync(soles);
        }
        
        public void setDtoS(double mon) {
            base.Channel.setDtoS(mon);
        }
        
        public System.Threading.Tasks.Task setDtoSAsync(double mon) {
            return base.Channel.setDtoSAsync(mon);
        }
        
        public void setStoD(double mon) {
            base.Channel.setStoD(mon);
        }
        
        public System.Threading.Tasks.Task setStoDAsync(double mon) {
            return base.Channel.setStoDAsync(mon);
        }
    }
}
